# Generated by Django 4.1.7 on 2023-04-04 05:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_img', models.ImageField(upload_to='articles')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('publication_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_img', models.ImageField(upload_to='customers')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_img', models.ImageField(upload_to='destinations')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('cost', models.PositiveIntegerField(verbose_name='Cost')),
                ('discount_price', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Discounted price')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)], verbose_name='Length')),
                ('plan_cost', models.PositiveIntegerField(default=0, verbose_name='Promotional cost')),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('opinion_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000, verbose_name='Comment')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.customers')),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.destinations')),
            ],
        ),
    ]
