# Generated by Django 4.1.7 on 2023-04-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_destinations_average_mark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='destination_img',
            new_name='destination_img_url',
        ),
    ]
