# Generated by Django 4.1.7 on 2023-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_rename_destination_img_url_destinations_destination_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publication_date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
    ]
