from .articlesSerializer import ArticlesSerializer
from .customersSerializer import CustomersSerializer
from .destinationsSerializer import DestinationsSerializer
from .opinionsSerializer import OpinionsSerializer
from .promotionsSerializer import PromotionsSerializer
